# Generated by Django 4.0.6 on 2022-07-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_alter_course_options_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
