# Generated by Django 4.0.6 on 2022-07-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='courses.tag'),
        ),
    ]
